import { Typography } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import { Counter } from "../components/counter";
import { ObjectComponent } from "../components/objectComponent";
import CountProvider from "../context/contextCounter";
import CtxObjectProvider from "../context/ctxObject";

const Home: NextPage = () => {
  // const { contextObject, setContextObject } = useContextObject();
  // setContextObject(0);
  // setContextObject({
  //   titleTextBold: "Vem cá!",
  //   section01IconCircleTextColor: false,
  // });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Typography variant="h1">DevALMO, YouTube channel</Typography>
        <CountProvider>
          <Counter />
        </CountProvider>

        <CtxObjectProvider>
          <ObjectComponent />
        </CtxObjectProvider>

        {/* <Typography>{contextObject.titleTextBold}</Typography> */}
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
